import { getSession, useSession } from 'next-auth/client'
import Head from 'next/head'
import Header from '../components/Header.js'
import Login from '../components/Login.js'
import Slider from '../components/Slider.js'
import Brands from '../components/Brands.js'

export default function Home() {
	const [session] = useSession()



	return (
		<div >
			<Head>
				<title>Disney+</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			{!session ?
				<Login /> : (
					<main className="relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
						<Slider />
						<Brands />
					</main>
				)
			}
		</div >
	)
}

export async function getServerSideProps(context) {
	const session = await getSession(context)

	return {
		props: {
			session,
		}
	}
}